name: Sanity Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Test latest stable, beta, dev channels + last stable release
        # prior to the introduction of the unified `dart` developer tool.
        sdk: [stable, beta, dev]
        flavor: [release]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          sdk: ${{ matrix.sdk }}

      - name: Sanity check with sdk ${{ matrix.sdk }} and os ${{ matrix.os }}
        run: |
          pub get
          dart format --set-exit-if-changed .
          dart analyze